# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventanaEstudiante.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(352, 555)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 170, 51, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 200, 101, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 230, 61, 16))
        self.nombreLineaEdicion = QLineEdit(self.centralwidget)
        self.nombreLineaEdicion.setObjectName(u"nombreLineaEdicion")
        self.nombreLineaEdicion.setGeometry(QRect(120, 170, 211, 20))
        self.nombreLineaEdicion.setAlignment(Qt.AlignCenter)
        self.correoLineaEdicion = QLineEdit(self.centralwidget)
        self.correoLineaEdicion.setObjectName(u"correoLineaEdicion")
        self.correoLineaEdicion.setGeometry(QRect(120, 200, 211, 20))
        self.correoLineaEdicion.setAlignment(Qt.AlignCenter)
        self.contraseniaLineaEdicion = QLineEdit(self.centralwidget)
        self.contraseniaLineaEdicion.setObjectName(u"contraseniaLineaEdicion")
        self.contraseniaLineaEdicion.setGeometry(QRect(120, 230, 211, 20))
        self.contraseniaLineaEdicion.setMaxLength(32767)
        self.contraseniaLineaEdicion.setFrame(True)
        self.contraseniaLineaEdicion.setCursorPosition(0)
        self.contraseniaLineaEdicion.setAlignment(Qt.AlignCenter)
        self.nombreEditorTexto = QTextEdit(self.centralwidget)
        self.nombreEditorTexto.setObjectName(u"nombreEditorTexto")
        self.nombreEditorTexto.setGeometry(QRect(10, 50, 331, 101))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 47, 14))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(150, 20, 61, 20))
        self.escrituraBoton = QPushButton(self.centralwidget)
        self.escrituraBoton.setObjectName(u"escrituraBoton")
        self.escrituraBoton.setGeometry(QRect(20, 260, 75, 23))
        self.lecturaBoton = QPushButton(self.centralwidget)
        self.lecturaBoton.setObjectName(u"lecturaBoton")
        self.lecturaBoton.setGeometry(QRect(100, 260, 75, 23))
        self.actualizacionBoton = QPushButton(self.centralwidget)
        self.actualizacionBoton.setObjectName(u"actualizacionBoton")
        self.actualizacionBoton.setGeometry(QRect(180, 260, 75, 23))
        self.eliminarBoton = QPushButton(self.centralwidget)
        self.eliminarBoton.setObjectName(u"eliminarBoton")
        self.eliminarBoton.setGeometry(QRect(260, 260, 75, 23))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 290, 331, 20))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 310, 331, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 330, 331, 16))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 350, 331, 16))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 370, 331, 20))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 390, 331, 20))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 430, 331, 20))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 410, 331, 16))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 450, 331, 20))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 470, 331, 20))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 490, 51, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 352, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Nombre: ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Correo Electr\u00f3nico:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Contrase\u00f1a:", None))
        self.nombreLineaEdicion.setInputMask("")
        self.nombreLineaEdicion.setText("")
        self.correoLineaEdicion.setText("")
        self.contraseniaLineaEdicion.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Tarea 5", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Estudiantes", None))
        self.escrituraBoton.setText(QCoreApplication.translate("MainWindow", u"Escritura", None))
        self.lecturaBoton.setText(QCoreApplication.translate("MainWindow", u"Lectura", None))
        self.actualizacionBoton.setText(QCoreApplication.translate("MainWindow", u"Actualizaci\u00f3n", None))
        self.eliminarBoton.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"* Para escribir alumno: Introducir la informaci\u00f3n de los 3 campos ", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"y presionar el bot\u00f3n \"Escribir\"", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"* Para leer alumno: Introducir la informaci\u00f3n del campo \"Nombre\" y", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"presionar el bot\u00f3n \"Lectura\"", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"* Para actualizar alumno: Introducir la informaci\u00f3n de los campos ", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\"Nombre\" y \"Contrase\u00f1a\". Despu\u00e9s presionar el bot\u00f3n ", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u" y volver a persionar el bot\u00f3n de \"Actualizaci\u00f3n\"", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\"Actualizaci\u00f3n\". En seguida llenar la informaci\u00f3n con los 3 campos", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"* Para eliminar alumno: Introcir la informaci\u00f3n de los campos", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\"Nombre\" y \"Contrase\u00f1a\". Despu\u00e9s presionar el bot\u00f3n ", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\"Eliminar\"", None))
    # retranslateUi

